#!/bin/bash

pandoc2rfc -R -t template.xml -x transform.xsl back.mkd middle.mkd

mv draft.txt draft-unpaginated.txt

for i in H N T X; 
  do bash pandoc2rfc -$i -t template.xml -x transform.xsl back.mkd middle.mkd; 
  done
